version: '3.7',
services:
  web:
    build: .
    environment:
      DATABASE_URL: postgres://db_user:pass@db:5432/nc_news
    ports: 
      - 9090:9090
    depends_on:
      - db
    db:
      image: postgres:12-alpine
      environment:
        POSTGRES_DB: nc_news
        POSTGRES_USER: db_user
        POSTGRES_PASS: pass
      volumes:
        - nc_news_data:/var/lib/postgresql/data

volumes:
  nc_news_data: